### PR TITLE
Add pre-commit pypgrade hook and update supported versions

### PR DESCRIPTION
**Pull request by hugovk**
* Update supported versions to match supported CPython versions
  * Add 3.6 and 3.7
  * Remove 3.2 and 3.3. They are EOL (and no longer receiving security updates (or any updates) from the core Python team.

Version | Release date | Supported until
--- | ---------- | ----------
3.2 | 2011-02-20 | 2016-02-27
3.3 | 2012-09-29 | 2017-09-29

They're also little used.

* Upgrade Python syntax with pyupgrade https://github.com/asottile/pyupgrade

* Fix flake8 warnings

### CODE REVIEW

**Comment by hugovk** [comment]
Yes, I'll add the pre-commit hook.

Shall I remove the `python_requires` line, would you rather keep it?

**Comment by hugovk** [comment]
Here's a test after `pip install pre-commit` and `pre-commit install`:
```
[hugo:/private/tmp/auth0-python] update-versions ± git checkout -b testing
Switched to a new branch 'testing'
[hugo:/private/tmp/auth0-python] testing ± edit setup.py
```
Add something that would fail pyupgrade:
```
[hugo:/private/tmp/auth0-python] testing ± git diff
```
```diff
diff --git a/setup.py b/setup.py
index dc7ba8a..afb41f4 100644
--- a/setup.py
+++ b/setup.py
@@ -17,7 +17,7 @@ def find_version():
 setup(
     name='auth0-python',
     version=find_version(),
-    description='Auth0 Python SDK',
+    description='Auth0 Python SDK {0}'.format(123),
     author='Auth0',
     author_email='support@auth0.com',
     license='MIT',
```
```
[hugo:/private/tmp/auth0-python] testing(+0/-0) ± git commit -m "Test pre-commit"
pyupgrade................................................................Failed
hookid: pyupgrade

Files were modified by this hook. Additional output:

Rewriting setup.py
⌂65% [hugo:/private/tmp/auth0-python] testing(+1/-1) 2s 1 ± git diff
```
```diff
diff --git a/setup.py b/setup.py
index afb41f4..1e41f7b 100644
--- a/setup.py
+++ b/setup.py
@@ -17,7 +17,7 @@ def find_version():
 setup(
     name='auth0-python',
     version=find_version(),
-    description='Auth0 Python SDK {0}'.format(123),
+    description='Auth0 Python SDK {}'.format(123),
     author='Auth0',
     author_email='support@auth0.com',
     license='MIT',
```
Now try and commit again:
```
[hugo:/private/tmp/auth0-python] testing(+1/-1) ± git add setup.py
# On branch: testing  |  [*] => $e*
#
➤ Changes to be committed
#
#       modified:  [1] setup.py
#
[hugo:/private/tmp/auth0-python] testing(+0/-0) ± git commit -m "Test pre-commit"
pyupgrade................................................................Passed
[testing 85adb54] Test pre-commit
 1 file changed, 1 insertion(+), 1 deletion(-)
```
Success! 🎆

**Comment by lbalmaceda** [comment]
@hugovk Thanks for all the details. ✨ I'd like to review the _security issue_ introduced with this `pre-commit` release (see failing _snyk_ check). Let me come back to this PR once I get a response from the team. 

Regarding `python_requires` I think it's better to rollback those 2 lines (3.2 and 3.3) so we don't break people today, but add a note somewhere in the README regarding compatibility standing that in the near future we will remove support for those versions as they have reached EOL (+ link to the notice). Also, why have you added new lines for `2` and `3` if we only support `2.7` (for 2) and well, eventually, `>3.3` ?

**Comment by hugovk** [comment]
> Regarding `python_requires` I think it's better to rollback those 2 lines (3.2 and 3.3) so we don't break people today, but add a note somewhere in the README regarding compatibility standing that in the near future we will remove support for those versions as they have reached EOL (+ link to the notice). 

Something like the last two commit?

---

> Also, why have you added new lines for `2` and `3` if we only support `2.7` (for 2) and well, eventually, `>3.3` ?

Because those don't mean that Python 2.0 and 3.0 are supported, but that at least one 2.x and 3.x versions are supported.

For example, the most-downloaded package [pip has these classifiers](https://github.com/pypa/pip/blob/6af9de97bbd2427f82942e476c590a2db22ea1ff/setup.py#L45-L52):

```python
        "Programming Language :: Python",
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.4",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
```

But I can remove them if you like.

**Comment by lbalmaceda** [comment]
@hugovk Yup. All good. Security has approved the PR as well. Thanks for the changes 👍

**Pull request merged**
