### PR TITLE
Add type hints to base and `authentication`

### LINKED ISSUE #470: Add type hints
As the project is now supporting Python3.7 and greater, we could add type hints. I'd be happy to work on this if this is an option.

For reference: https://typing.readthedocs.io/en/latest/source/libraries.html

Tracked PRs:

- https://github.com/auth0/auth0-python/pull/472
- https://github.com/auth0/auth0-python/pull/497

### PR DESCRIPTION
**Pull request by Viicos**
Fixes partially #470.
The goal is not to add complete type hints to the library, but only were it is beneficial. There are some code patterns that break mypy rules (e.g.  Liskov substitution principle), and I'm not aiming at doing refactors, so once most of the type hints will be added, I'll write a mypy configuration accordingly.

I'm going for the `from __future import annotations` import, to improve type hints readability.

Noticed a couple things:

- This has been introduced two years ago, should it be deprecated now?
https://github.com/auth0/auth0-python/blob/44d6d0ec5c0a098a6d333e7f24d784416da07bca/auth0/rest.py#L108-L111

- Could these methods be transformed into properties/class variables?
https://github.com/auth0/auth0-python/blob/44d6d0ec5c0a098a6d333e7f24d784416da07bca/auth0/rest.py#L113-L127

### CODE REVIEW

**Comment by adamjmcgrath** [comment]
Thanks @Viicos - this PR looks good - just need to fix the build

 > This has been introduced two years ago, should it be deprecated now?

I should have done it when I did the last major, but I missed it - will have to wait until the next major

> Could these methods be transformed into properties/class variables?

Sure, but I'll need to look at this in the next major

**Comment by Viicos** [comment]
Understandable as this would be a breaking change. I'll continue to add some type hints while still being careful not to overwhelm the code base.

**Comment by adamjmcgrath** [comment]
Hi @Viicos - is adding type hints a breaking change, I thought since the project was now >=3.7 this could be introduced in a non breaking way?

**Comment by Viicos** [comment]
> Hi @Viicos - is adding type hints a breaking change, I thought since the project was now >=3.7 this could be introduced in a non breaking way?

Hi, sorry I was replying to your answer regarding the second point I asked in this PR description:
>Could these methods be transformed into properties/class variables?

Switching to properties would be a breaking change as using `RestClient().MAX_REQUEST_RETRIES()` would result in a `TypeError`. Regarding type hints it's not breaking anything indeed if using Python>3.5

**Comment by Viicos** [comment]
I think I'll probably make another PR regarding the `management` module for simplicity. The only things left on this one:
- Fix doc build error
- Define better return types for authentification classes: To keep things simple, I'll only return the general type, e.g. `dict[str, Any]` or `str` and will not make use of `TypedDict`.

**Comment by Viicos** [comment]
I still have a few `mypy` errors to correct, but in the meanwhile I noticed a few optionals that shouldn't be:

- https://github.com/auth0/auth0-python/blob/c8f2d65051a6586df73f525a6e0d6cbbafa990a9/auth0/authentication/token_verifier.py#L141-L142
`_fetcher` is of type `JwksFetcher`, and `get_key` excepts `key_id` to be a string, not `str | None`.

- https://github.com/auth0/auth0-python/blob/c8f2d65051a6586df73f525a6e0d6cbbafa990a9/auth0/authentication/client_authentication.py#L7-L34
`jwt.encode` excepts `client_assertion_signing_key` to be a string, not `str | None`.

- https://github.com/auth0/auth0-python/blob/c8f2d65051a6586df73f525a6e0d6cbbafa990a9/auth0/rest_async.py#L100-L103
`data` and `files` can't be `None` here, as `{**data, **files}` would fail otherwise.

I'll let you decide on these three cases what should be done (e.g. removing the default `None` values)

**Comment by adamjmcgrath** [comment]
Thanks for spotting those @Viicos! You can make them all required arguments 👍

**Comment by Viicos** [comment]
Had to ignore a few `mypy` error codes to avoid having to refactor some parts, but otherwise looks good. Some API return types have been left to `Any`, as the openapi docs doesn't specify any return examples

**Comment by Viicos** [comment]
@adamjmcgrath I think this one is ready. I have a failing test on 3.10 due to this error on docs:

> /home/circleci/project/auth0/authentication/token_verifier.py:docstring of auth0.authentication.token_verifier.JwksFetcher.get_key:1: WARNING: py:class reference target not found: RSAPublicKey

Do you happen to know how this can be fixed?

**Comment by Viicos** [comment]
Hi @adamjmcgrath, in case you did not get notified, this one is ready for review/merge

**Comment by adamjmcgrath** [comment]
lgtm, thanks @Viicos - can you just resolve that conflict and I'll approve and merge 👍

**Comment by Viicos** [comment]
@adamjmcgrath If the last edit @https://github.com/auth0/auth0-python/pull/472/commits/b8a4a2c7d96ce510bf142a9f4323c9986f7f76b0 is good, I think this can be merged

**Pull request merged**
