### PR TITLE
fixed typo by changing '.' to ','

### PR DESCRIPTION
**Pull request by beck3905**

### CODE REVIEW

**Comment by beck3905** [comment]
@lbalmaceda - This is a very minor fix to a bug in the latest version that causes the management API not to work.  Could you please review and release this as soon as possible?  Thanks.

**Comment by beck3905** [comment]
@lbalmaceda - Done!

**Comment by beck3905** [comment]
@lbalmaceda - Thank you.  When will the next release with this fix be available on PyPi?

**Comment by lbalmaceda** [comment]
It's already there 😉 under `3.6.1`

**Comment by beck3905** [comment]
Just saw it come through.  Thanks.

**Pull request merged**
