### PR TITLE
Add GitHub issue and pull request templates

### PR DESCRIPTION
**Pull request by anatolyyyyyy**

### CODE REVIEW

**Comment by anatolyyyyyy** [comment]
hi @joshcanhelp I do not understand a bit what needs to be changed. What internal templates do you mean?

**Comment by joshcanhelp** [comment]
@anatolyyyyyy - Apologies, I meant to post a link to our templates:

https://github.com/auth0/open-source-template/tree/master/.github

**Comment by anatolyyyyyy** [comment]
@joshcanhelp - updated

**Comment by joshcanhelp** [comment]
@anatolyyyyyy - Going to close this one out and handle internally. Thank you regardless!

**Pull request closed without merging**
